# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e100217d923d1d3ab6a168efae2ad7743f5cd46efe757fde16545e3b576c4f079851669622096af00069a55537637dc5f46ff9d192cd78ff88f2d14fb35c018b

test:
  secret_key_base: 12850ce648096d677860342ee299894e0cce514af698f018e9bb66d580a9705099a06b67ed6f9e4e70f456e6958b7d3af5bddb8fc4607184801a95262bb84c89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
